name: validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            docs
            style
            refactor
            test
            ci
            chore
            build
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The description "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the description
            doesn't start with an uppercase character.
          wip: true

      - uses: marocchino/sticky-pull-request-comment@v2.3.1
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Our pull requests titles follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - uses: marocchino/sticky-pull-request-comment@v2.3.1
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:   
          header: pr-title-lint-error
          delete: true